### ISSUE TITLE
npm install with Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by orangeullr** [lintaba/chatbot-for-pizza#1]
Attempting an npm install command after a clone request gave me the following output.

uname@machine:~/Directory$ npm install .

> sleep@4.0.0 install ~/Directory
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-72-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd ~/Directory
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN pizzaorder-chatbot@1.0.0 No description
npm WARN pizzaorder-chatbot@1.0.0 No repository field.
npm ERR! Linux 4.4.0-72-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "."
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sleep@4.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sleep@4.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sleep package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sleep
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sleep
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

It seems to be an issue with installing the sleep module.

NodeJS is v4.2.6
npm is v3.5.2

I'm using Ubuntu 16.04 LTS
and running kernel version 4.4.0-72-generic

Just giving you a heads up.
Thanks!

**Comment by lintaba** [comment]
Check your node version, and update it to match the minimal version:
```
  "engines": {
    "node": ">=6.0.0"
  },
```
